### ISSUE TITLE
Orders retour

### ISSUE THREAD

**Issue by subblyold** [subblyold/cms#1]
- Enlever le dégradé au scroll en dessous de la barre de recherche(je t'ai vu Mike à récupérer ton ancien dégradé Tapioca)
- Enlever fond blanc au hover sur le input search 
- Le hover bleu sur une commande doit dépasser sur la border top et bottom (pour pas avoir le pixel gris au dessus et en dessous)
- Sur mon laptop (1400px de large et quelques) la 3eme colonne s'arrête à 1200 (ce qui est normal je crois?) mais du coup je trouve ça dommage, ça mériterai d'élargir la largeur max à 1400 (ou plus à voir)

**Comment by michael-lefebvre** [comment]
> > Enlever le dégradé au scroll en dessous de la barre de recherche(je t'ai vu Mike à récupérer ton ancien dégradé Tapioca)

attend d'avoir vu la version avec JS et le "sticky" formulaire de recherche pour décider ! une fois correctement défini ça rend le truc smooth...

> > blahblah 1200, blahblah 1400  

ok, mais le souci c'est pas les grandes résolutions mais les petites, à voir au prochain commit, mais les noms de produits trop long plantes la mise en page sur écran inferieur à 1130px...
