### ISSUE TITLE
API, products position

### ISSUE THREAD

**Issue by michael-lefebvre** [subblyold/cms#16]
Comment qu'on gère l'ordre des produits ? Niveau UI, je vais passer par du drag/drop classique, du coup je peux retourner la nouvelle position de chacun des produits visibles dans la vue (uniquement ceux que j'ai récupéré  au moment du "re-order"), mais que ça soit en front ou en back je ne suis pas sûr que ce soit une bonne idée de faire une boucle de `PUT`...

![pq43as](https://cloud.githubusercontent.com/assets/279053/5079469/1777f08a-6eb5-11e4-81d2-7c75d315febd.jpg)

de ce que je vois de l'API de `spatie/eloquent-sortable`, il faut lui passer la nouvelle position de tous produits. Est ce que l'on peu imaginer une route dans l'API `products` dédié à cette tâche à qui j'enverrai le tableau du nouvel ordre, ou tu vois une autre méthode ?

quid des produits dont je ne peux pas te donner la nouvelles positions ?

**Comment by nicolas-brousse** [comment]
Il faudrait voir. Car pagination + ordering, c'est toujours sympa :)
