### ISSUE TITLE
API global, sort by

### ISSUE THREAD

**Issue by michael-lefebvre** [subblyold/cms#19]
ajouter un paramètre qui permet de définir le champs de tri et le sens. Exemple, actuellement les produits sortent par date d'ajout croissant, c'est pas pratique.

**Comment by nicolas-brousse** [comment]
Resolved with commits:
- https://github.com/subbly/framework/commit/4db762c806f1c65514608c474c89416fb9dc865f
- https://github.com/subbly/framework/commit/1431ea563e4a5eb5153f29fab87d67a61709e06d
- https://github.com/subbly/framework/commit/817eaf8ed244aa2a0d309a2a8a04ab6e07e49689
