### ISSUE TITLE
Upload media

### ISSUE THREAD

**Issue by michael-lefebvre** [subblyold/cms#20]
à discuter.

**Comment by michael-lefebvre** [comment]
upload ajax : 
https://github.com/blueimp/jQuery-File-Upload

**Comment by nicolas-brousse** [comment]
https://github.com/subbly/framework/commit/06741cf3c578c7693662893f519f04931381963e

Upload is now possible with this commit.
`POST /api/v1/products/SKUProduct/images` the file field must be named `product_image`.

**Comment by michael-lefebvre** [comment]
test done with success but API must return the file full public's path, not just the file name.
