### ISSUE TITLE
Settings, batch update

### ISSUE THREAD

**Issue by michael-lefebvre** [subblyold/cms#28]
l'update clés par clés n'est pas pratique au vue de l'UI. On peu le garder mais il faudrait la possibilité de pouvoir updater une série de clés en un seul appel.

**Comment by nicolas-brousse** [comment]
Ok.
Mais du coup, c'est en vue de permettre un lot d'action restreint pour un groupe ?

**Comment by michael-lefebvre** [comment]
pas sur de comprendre. tu voudrais que je fasse des boucles dans le BO pour mettre à jour les clés ?
