### ISSUE TITLE
Settings, ajout de nouvelles clés

### ISSUE THREAD

**Issue by michael-lefebvre** [subblyold/cms#29]
ne pas bloquer les settings aux clés existantes

**Comment by nicolas-brousse** [comment]
Actuellement les settings doivent êtres déclarées dans un fichier yaml : https://github.com/subbly/framework/blob/master/src/Subbly/Resources/configs/default_settings.yml

**Comment by michael-lefebvre** [comment]
le souci est que le système doit pouvoir accueillir les clés issues de plugins.
je pense que ce serait plus simple si le fichier regroupait les valeurs par défaut et les injecte en base lors de l'install. tu en penses quoi ?
