### ISSUE TITLE
Users group

### ISSUE THREAD

**Issue by michael-lefebvre** [subblyold/cms#3]
Pouvoir ajouter un utilisateur aux groupes 'admin' ou 'client' et pouvoir filtrer les requêtes par groupe.

**Comment by nicolas-brousse** [comment]
Quelles requêtes sont à filtrer ?

**Comment by michael-lefebvre** [comment]
par exemple, dans le BO, quand tu veux lister les utilisateurs du BO ou juste les clients. Il faut aussi garantir que l'accès au BO n'est disponible qu'au utilisateurs valides, et pas à n'importe quelle client avec un couple login/password correct

**Comment by nicolas-brousse** [comment]
Ok, je vais tâcher de commencer à implémenter ça demain.

**Comment by nicolas-brousse** [comment]
Comment tu imagines filtrer pour les groupes ?
D'un point de vue interface ?

Car pour le moment le search by c'est soit un string qui va chercher dans plusieurs champs, soit un array : http://subbly.github.io/documentation/core-api/api/master/Subbly/Api/Service/UserService.html#method_searchBy.

Faudrait échanger un peu plus pour la recherche, afin que je mette à jour de manière cohérente par rapport à ce que tu aimerais.

En ce qui concerne l'ajout à la création, je suis en train de voir de quelles façons je pourrait m'y prendre.
Même question, sous quelle format tu aurais imaginé envoyé la/les données.

**Comment by nicolas-brousse** [comment]
#12
